[package]
name = "rgnav"
version = "0.1.0"
edition = "2021"


[dependencies]
ratatui = "*"
crossterm = "*"
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
ansi-to-tui = "*"
atty = "*"
